FROM python:3.11-slim

# Desactivar buffering de python para visualización de logs inmediata
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY . .

# Exponer el puerto de Streamlit
EXPOSE 8501

# Arrancar la aplicación Streamlit
CMD ["streamlit", "run", "src/frontend/app_ui.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
